<?php
$allowedRoles=['super_admin','admin','manager','supervisor','Admin','ro-super-admin','ro-admin','ro-manager','ro-supervisor'];
require_once '../../config/db_connection.php';require_once '../../config/require_auth.php';require_once 'purchase_order_helpers.php';
if($_SERVER['REQUEST_METHOD']!=='GET'){http_response_code(405);echo json_encode(['status'=>'error','message'=>'Only GET requests are allowed.']);exit();}
try{
$rows=$pdo->query("SELECT ib.batch_id AS inventory_batch_id,ib.po_item_id,po.po_id,po.po_number,s.supplier_name,COALESCE(NULLIF(poi.product_name_snapshot,''),p.product_name) product_name,COALESCE(NULLIF(poi.brand_name_snapshot,''),p.brand_name) brand_name,ib.storage_qty,ib.shelf_qty,ib.storage_qty+ib.shelf_qty usable_quantity,COALESCE(pi.batch_number,ib.batch_id) batch_number,ib.expiry_date,sp.supplier_product_id FROM inventory_batches ib INNER JOIN purchase_order_items poi ON poi.po_item_id=ib.po_item_id INNER JOIN purchase_orders po ON po.po_id=poi.po_id AND po.status='Delivered' INNER JOIN suppliers s ON s.supplier_id=po.supplier_id INNER JOIN product p ON p.product_id=poi.product_id INNER JOIN supplier_products sp ON sp.supplier_id=po.supplier_id AND sp.product_id=poi.product_id LEFT JOIN product_inventory pi ON pi.inventory_id=ib.legacy_inventory_id WHERE ib.storage_qty+ib.shelf_qty>0 ORDER BY po.created_at DESC,po.po_number,product_name")->fetchAll(PDO::FETCH_ASSOC);
 $conversionStatement=$pdo->prepare('SELECT conversion_id,unit_name,base_quantity,level_order FROM supplier_product_unit_conversions WHERE supplier_product_id=:supplier_product_id ORDER BY level_order DESC,base_quantity DESC');
 foreach($rows as &$row){$row['storage_qty']=(int)$row['storage_qty'];$row['shelf_qty']=(int)$row['shelf_qty'];$row['usable_quantity']=(int)$row['usable_quantity'];$conversionStatement->execute([':supplier_product_id'=>$row['supplier_product_id']]);$row['package_conversions']=$conversionStatement->fetchAll(PDO::FETCH_ASSOC);foreach($row['package_conversions'] as &$conversion)$conversion['base_quantity']=(int)$conversion['base_quantity'];unset($conversion);unset($row['supplier_product_id']);}unset($row);
 echo json_encode(['status'=>'success','sources'=>$rows]);
}catch(Throwable $e){http_response_code(500);echo json_encode(['status'=>'error','message'=>'Unable to load claim source batches.','error'=>$e->getMessage()]);}
