import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const products = await readFile(new URL('../pharma-frontend/js/modules/products.js', import.meta.url), 'utf8');
const suppliers = await readFile(new URL('../pharma-frontend/js/modules/suppliers.js', import.meta.url), 'utf8');
const loader = await readFile(new URL('../pharma-frontend/js/modules/measurement_units.js', import.meta.url), 'utf8');
const page = await readFile(new URL('../pharma-frontend/products.html', import.meta.url), 'utf8');
const measurementUnitModal = page.slice(page.indexOf('id="addMeasurementUnitModal"'), page.indexOf('id="editProductModal"'));
const productTypeModal = page.slice(page.indexOf('id="addProductTypeModal"'), page.indexOf('id="customizeSpecificationsModal"'));

assert.match(loader, /get_measurement_units\.php/);
assert.match(loader, /measurementUnitsForContext/);
assert.match(loader, /context = ''/);
assert.match(loader, /ACTIVE_SNAPSHOT_MAX_AGE_MS = 5000/);
assert.match(products, /loadMeasurementUnits/);
assert.match(products, /loadMeasurementUnitCache\(\{ forceRefresh: true \}\)/);
assert.match(products, /measurementUnitOptionList\('Volume'/);
assert.match(products, /measurementUnitOptionList\('Weight'/);
assert.doesNotMatch(products, /measurementUnitOptionList\(variation\.net_content_unit/);
assert.match(suppliers, /loadSharedMeasurementUnits/);
assert.doesNotMatch(products, /\['Weight', 'Volume', 'Strength', 'Count', 'Length', 'General Size'\]/);
assert.match(products, /Number\(unit\.is_active \?\? 1\) === 1/);
assert.match(products, /— archived/);
assert.match(products, /historicalUnitMatchesGroup/);
assert.match(products, /delete_measurement_unit\.php/);
assert.match(products, /delete-measurement-unit-option/);
assert.doesNotMatch(products, /measurementUnitSelectAll/);
assert.doesNotMatch(products, /btnDeleteSelectedMeasurementUnits/);
assert.doesNotMatch(products, /measurement-unit-checkbox/);
assert.match(products, /const isSystem = Number\(unit\.is_system \?\? 1\) === 1/);
assert.match(products, /<span>Unit<\/span><span>Symbol<\/span><span>Group<\/span><span>Actions<\/span>/);
assert.doesNotMatch(products, /select-measurement-unit-option/);
assert.doesNotMatch(products, /MEDICINE_(?:STRENGTH|VOLUME)_UNITS/);
assert.match(products, /MEASUREMENT_SELECT_SELECTOR/);
assert.match(products, /measurement-select-trigger/);
assert.match(products, /trigger\.setAttribute\('role', 'combobox'\)/);
assert.match(products, /select\.setAttribute\('aria-hidden', 'true'\)/);
assert.match(products, /selectMeasurementUnitFromManager/);
assert.match(products, /title="Edit unit"/);
assert.match(products, /Built-in measurement unit cannot be deleted/);
assert.match(products, /system-measurement-unit-delete/);
assert.match(products, /measurementUnitDisplayLabel/);
assert.match(products, /Are you sure you want to delete.*measurementUnitDisplayLabel/);
assert.match(products, /if \(!unit\) throw new Error\('Unable to delete measurement unit\.'\)/);
assert.match(products, /console\.error\('Unable to delete measurement unit\.'/);
assert.match(products, /PharmaUtils\.toast\.error\(message\)/);
assert.match(products, /<span>Manage Units<\/span>/);
assert.doesNotMatch(products, /Customize \/ Add Measurement Units/);
assert.match(products, /event\.preventDefault\(\);\s*event\.stopPropagation\(\);/);
assert.match(products, /setMeasurementUnitEditorMode/);
assert.doesNotMatch(products, />Protected</);
assert.match(page, /#addMeasurementUnitModal \.modal-dialog \{ width:min\(800px,calc\(100vw - 24px\)\); height:min\(80vh,760px\); \}/);
assert.match(page, /#addMeasurementUnitModal \.customizer-list \{ flex:1 1 300px; min-height:220px; max-height:none; overflow:auto; \}/);
assert.match(page, /\.measurement-select-trigger \{[^}]*height:42px;[^}]*min-height:42px;/);
assert.match(page, /\.measurement-select-menu \{[^}]*position:fixed;[^}]*z-index:1105;/);
assert.match(page, /\.measurement-select-menu \{[^}]*min-width:180px;/);
assert.match(page, /\.measurement-select-option \{[^}]*min-height:36px;[^}]*font-size:12\.75px;[^}]*white-space:nowrap;/);
assert.match(page, /\.system-measurement-unit-delete \{[^}]*cursor:not-allowed;/);
assert.match(page, /\.system-measurement-unit-delete \.btn:disabled \{ pointer-events:none; \}/);
assert.match(measurementUnitModal, /id="btnCancelMeasurementUnit"/);
assert.match(measurementUnitModal, /id="btnSaveMeasurementUnit"/);
assert.doesNotMatch(productTypeModal, /btn(?:Cancel|Save)MeasurementUnit/);
assert.doesNotMatch(page, /Delete Selected/);

console.log('Measurement unit UI integration tests passed.');
