<?php
declare(strict_types=1);
require_once __DIR__.'/../pharma-api/config/db_connection.php';
function smokeAssert(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
$user=$pdo->query("SELECT user_id,username,full_name,role,status FROM users WHERE role='admin' AND status='Active' LIMIT 1")->fetch(PDO::FETCH_ASSOC);smokeAssert((bool)$user,'Active admin fixture required.');
if(session_status()===PHP_SESSION_ACTIVE)session_write_close();$phpSessionId='codexclaim'.bin2hex(random_bytes(10));$tabToken=bin2hex(random_bytes(32));$authSessionId=newUuid($pdo);session_id($phpSessionId);session_start();$_SESSION=['user_id'=>$user['user_id'],'username'=>$user['username'],'full_name'=>$user['full_name'],'role'=>$user['role'],'roles'=>[$user['role']],'role_identifiers'=>['ro-admin'],'user_status'=>$user['status'],'auth_session_id'=>$authSessionId,'tab_token_hash'=>hash('sha256',$tabToken)];session_write_close();
$pdo->prepare('INSERT INTO auth_sessions(auth_session_id,php_session_id,user_id,session_token_hash,expires_at,ip_address,user_agent) VALUES(:id,:php,:user,:token,DATE_ADD(NOW(),INTERVAL 10 MINUTE),\'127.0.0.1\',\'Codex claim smoke\')')->execute([':id'=>$authSessionId,':php'=>$phpSessionId,':user'=>$user['user_id'],':token'=>hash('sha256',$tabToken)]);
function smokeGet(string $path,string $sessionId,string $token):array{$curl=curl_init('http://127.0.0.1/PharmacySystem_for_DocR/pharma-api/v1/'.$path);curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_COOKIE=>'PHPSESSID='.$sessionId,CURLOPT_HTTPHEADER=>['Accept: application/json','X-Tab-Token: '.$token],CURLOPT_TIMEOUT=>20]);$body=curl_exec($curl);$status=(int)curl_getinfo($curl,CURLINFO_RESPONSE_CODE);$error=curl_error($curl);curl_close($curl);smokeAssert($body!==false,'HTTP failure: '.$error);return ['status'=>$status,'body'=>json_decode((string)$body,true)?:[]];}
try{$poId=(string)$pdo->query('SELECT po_id FROM purchase_orders ORDER BY created_at DESC LIMIT 1')->fetchColumn();foreach(['purchase_orders/get_purchase_orders.php?scope=all','purchase_orders/get_purchase_order.php?po_id='.rawurlencode($poId),'purchase_orders/get_return_damage_orders.php','purchase_orders/get_supplier_claim_sources.php','purchase_orders/get_supplier_credits.php?po_id='.rawurlencode($poId)] as $path){$response=smokeGet($path,$phpSessionId,$tabToken);smokeAssert($response['status']===200,"{$path} failed: ".json_encode($response));}$claimId=(string)$pdo->query('SELECT claim_id FROM supplier_claims ORDER BY created_at DESC LIMIT 1')->fetchColumn();if($claimId!==''){$details=smokeGet('purchase_orders/get_return_damage_details.php?return_id='.rawurlencode($claimId),$phpSessionId,$tabToken);smokeAssert($details['status']===200,'Return/damage details failed: '.json_encode($details));smokeAssert(array_key_exists('activities',$details['body']['return_damage']??[]),'Return/damage details did not expose traceable activity.');}echo "purchase order claim HTTP smoke test passed\n";}finally{$pdo->prepare('DELETE FROM auth_sessions WHERE auth_session_id=:id')->execute([':id'=>$authSessionId]);}
