CREATE TABLE IF NOT EXISTS inventory_resolution_cases (
    case_id CHAR(36) NOT NULL PRIMARY KEY,
    case_seq BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    batch_id CHAR(36) NOT NULL,
    product_id CHAR(36) NOT NULL,
    supplier_id CHAR(36) NULL,
    case_type ENUM('Return','Disposal') NOT NULL,
    status VARCHAR(32) NOT NULL,
    reason VARCHAR(100) NOT NULL,
    expected_resolution ENUM('Replacement','Credit') NULL,
    shelf_qty INT NOT NULL DEFAULT 0,
    storage_qty INT NOT NULL DEFAULT 0,
    unit_cost DECIMAL(12,4) NOT NULL DEFAULT 0,
    disposal_method VARCHAR(120) NULL,
    scheduled_date DATE NULL,
    witness VARCHAR(100) NULL,
    note TEXT NULL,
    reference_number VARCHAR(100) NULL,
    credit_amount DECIMAL(12,2) NULL,
    received_qty INT NOT NULL DEFAULT 0,
    replacement_batch_id CHAR(36) NULL,
    created_by CHAR(36) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    closed_at TIMESTAMP NULL,
    KEY idx_resolution_batch_status (batch_id,status),
    KEY idx_resolution_status_updated (status,updated_at),
    CONSTRAINT fk_resolution_batch FOREIGN KEY (batch_id) REFERENCES inventory_batches(batch_id),
    CONSTRAINT fk_resolution_product FOREIGN KEY (product_id) REFERENCES product(product_id),
    CONSTRAINT fk_resolution_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id),
    CONSTRAINT chk_resolution_qty CHECK (shelf_qty >= 0 AND storage_qty >= 0 AND shelf_qty + storage_qty > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS inventory_resolution_case_events (
    event_id CHAR(36) NOT NULL PRIMARY KEY,
    case_id CHAR(36) NOT NULL,
    status VARCHAR(32) NOT NULL,
    description VARCHAR(500) NOT NULL,
    reference_number VARCHAR(100) NULL,
    actor_id CHAR(36) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_resolution_event_case (case_id,created_at),
    CONSTRAINT fk_resolution_event_case FOREIGN KEY (case_id) REFERENCES inventory_resolution_cases(case_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
