import PharmaUtils from '../utils.js';
import { createLiveSync, publishDataUpdate } from './live_data.js?v=1';
import { cleanProductSpecificationText, formatProductIdentityParts, isPrescriptionProduct } from './product_specification.js?v=9';

const API_BASE_URL = window.location.port ? 'http://127.0.0.1/PharmacySystem_for_DocR/pharma-api/v1' : '../pharma-api/v1';
const SEP = PharmaUtils.productIdentitySeparator || ' • ';
let shelfRows = [];
let shelfLoaded = false;

const esc = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const text = value => String(value ?? '').trim();
const cleanNumber = value => text(value) && Number.isFinite(Number(value)) ? String(Number(value)) : text(value);
const measurement = (value,unit) => cleanNumber(value) ? `${cleanNumber(value)}${text(unit) ? ` ${text(unit)}` : ''}` : '';
const pretty = value => text(value) && !/\d/.test(text(value)) && text(value) === text(value).toLowerCase() ? text(value)[0].toUpperCase()+text(value).slice(1) : text(value);
function unique(parts){const seen=new Set();return parts.map(pretty).filter(part=>{const key=part.toLowerCase();if(!part||seen.has(key))return false;seen.add(key);return true;});}
function productIdentity(row){return text(row?.product_name)||formatProductIdentityParts(row).productName||'';}
function productGeneric(row){return text(row?.generic_name)||'';}
function rxBadge(row){return isPrescriptionProduct({medicine_classification_badge:row?.medicine_classification_badge,medicine_classification:row?.medicine_classification,...row})?'<span class="shelf-rx-badge" title="Prescription medicine">Rx</span>':'';}
function productCell(row){const parts=formatProductIdentityParts(row);return parts.productName?`<span class="shelf-product-identity"><strong>${esc(parts.productName)}</strong>${rxBadge(row)}</span>${parts.genericName?`<small class="d-block text-muted shelf-generic-name">${esc(parts.genericName)}</small>`:''}`:'<span class="text-muted">—</span>';}
function unitLabel(value,quantity=1){const raw=text(value)||'Unit';const normalized=raw.toLowerCase().replaceAll('.','');const singular=['pc','pcs','piece','pieces','each'].includes(normalized)?'Piece':raw.split(/\s+/).map(word=>word?word[0].toUpperCase()+word.slice(1).toLowerCase():'').join(' ');if(Number(quantity)===1||/s$/i.test(singular))return singular;if(/(?:x|z|ch|sh)$/i.test(singular))return `${singular}es`;return `${singular}s`;}
function specification(product){
    const cleanSpec=cleanProductSpecificationText(product.normalized_specification);
    if(text(cleanSpec)){const inventoryUnit=unitLabel(product.inventory_unit_name||product.inventory_unit_symbol);return unique(text(cleanSpec).split(/\s*•\s*/).map(part=>{const content=part.match(/^(\d+(?:\.\d+)?)\s*(?:pc|pcs|piece|pieces)$/i);return content&&!/^pieces?$/i.test(inventoryUnit)?`${content[1]} Pieces per ${inventoryUnit}`:part;})).join(SEP);}
    const category=text(product.category_name).toLowerCase(); let parts=[];
    if(category==='medicine') parts=[measurement(product.strength_value,product.strength_unit)||product.strength,measurement(product.net_content_value,product.net_content_unit),product.dosage_form];
    else if(category==='medical supply'||category==='medical supplies') parts=[product.medical_variant,product.medical_size,product.material,product.sterile_status];
    else { const weight=measurement(product.net_weight,product.unit); parts=[product.variant,weight?'':product.size,weight]; }
    return unique(parts.filter(text)).join(SEP)||'No specification available';
}
function formatDate(value){if(!value)return '-';const date=new Date(`${value}T00:00:00`);return Number.isNaN(date.getTime())?'-':date.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
function expiryBadge(row){const status=text(row.expiry_status)||'N/A';const cls=status==='Safe'?'status-safe':status==='Expiring Soon'?'status-soon':status==='Expired'?'status-expired':'status-na';return `<span class="status-pill ${cls}">${esc(status)}</span><small class="d-block mt-1 text-muted">${esc(formatDate(row.nearest_expiry_date))}</small>`;}
function statusPill(status){const value=text(status)||'N/A';const cls=value==='Safe'?'status-safe':value==='Expiring Soon'?'status-soon':value==='Expired'?'status-expired':'status-na';return `<span class="status-pill ${cls}">${esc(value)}</span>`;}
function detailPair(label,value){return `<div class="product-details-pair"><dt>${esc(label)}</dt><dd>${value}</dd></div>`;}
function openShelfDetails(productId){const row=shelfRows.find(item=>String(item.product_id)===String(productId));if(!row)return;const name=text(row.product_name)||productIdentity(row)||'Product';const generic=text(row.generic_name)||'—';const unit=unitLabel(row.inventory_unit_name||row.inventory_unit_symbol||'unit',Number(row.shelf_quantity));const nearest=`${esc(row.expiry_status||'—')}${row.nearest_expiry_date?` • ${esc(formatDate(row.nearest_expiry_date))}`:''}`;document.getElementById('shelfDetailsModalTitle').textContent='Shelf Details';document.getElementById('shelfDetailsIdentityLine').innerHTML=`<strong>${esc(name)}</strong>${generic!=='—'?`<span>${esc(generic)}</span>`:''}`;const batches=Array.isArray(row.batches)?row.batches:[];document.getElementById('shelfDetailsContent').innerHTML=`<section class="product-details-section"><dl class="product-details-list">${detailPair('Brand',esc(row.brand_name||'—'))}${detailPair('Product Name',esc(name))}${detailPair('Generic Name',esc(generic))}${detailPair('Specification',esc(specification(row)))}${detailPair('Product Type',esc(row.type_name||'—'))}${detailPair('Rx / OTC Tag',rxBadge(row)||'<span class="text-muted">—</span>')}${detailPair('Total Shelf Qty',`${esc(row.shelf_quantity)} ${esc(unit)}`)}${detailPair('Nearest Expiry',nearest)}</dl></section><section class="product-details-section"><h6>Shelf Batches</h6><div class="shelf-batch-table"><div class="shelf-batch-row shelf-batch-head"><span>Batch/Lot No.</span><span>Expiry Date</span><span>Shelf Qty Remaining</span><span>Expiry Status</span></div>${batches.map(batch=>`<div class="shelf-batch-row"><span class="shelf-batch-cell shelf-batch-value" title="${esc(batch.batch_number||batch.batch_id||'')}">${esc(formatBatchText(batch.display_batch_number||'Not recorded'))}</span><span class="shelf-batch-cell">${esc(formatDate(batch.expiry_date))}</span><span class="shelf-batch-cell">${esc(batch.shelf_quantity)}</span><span class="shelf-batch-cell">${statusPill(batch.expiry_status)}</span></div>`).join('')||'<div class="shelf-batch-row"><span class="shelf-batch-cell">No shelf batches found.</span><span></span><span></span><span></span></div>'}</div></section>`;bootstrap.Modal.getOrCreateInstance(document.getElementById('shelfDetailsModal')).show();}

function filteredRows(){const query=text(document.getElementById('shelfSearch')?.value).toLowerCase();const type=text(document.getElementById('shelfTypeFilter')?.value);const status=text(document.getElementById('shelfStatusFilter')?.value);return shelfRows.filter(row=>(!query||[row.brand_name,productIdentity(row),row.generic_name,row.barcode,row.type_name,row.medicine_classification,specification(row)].join(' ').toLowerCase().includes(query))&&(!type||row.type_name===type)&&(!status||row.pos_status===status));}
function formatBatchText(value){const raw=text(value)||'Not recorded';return raw.split('-').map((part,index,parts)=>`${part}${index<parts.length-1?'-':''}`).join('\n');}
function batchBadges(row){const batches=Array.isArray(row.batches)?row.batches:[];const visible=batches.slice(0,3);if(!visible.length)return `<span class="shelf-batch-value" title="${esc(row.batch_display||'Not recorded')}">${esc(formatBatchText(row.batch_display||'Not recorded'))}</span>`;const more=batches.length-visible.length;return `<div class="shelf-batch-list">${visible.map(batch=>`<span class="shelf-batch-value" title="${esc(batch.batch_number||batch.batch_id||'')}">${esc(formatBatchText(batch.display_batch_number||'Not recorded'))}</span>`).join('')}${more>0?`<span class="shelf-batch-more">+${esc(more)} more</span>`:''}</div>`;}
function render(){const body=document.querySelector('#shelfInventoryTable tbody');const rows=filteredRows();if(!rows.length){body.innerHTML='<tr><td colspan="10" class="empty-row">No transferred Shelf stock matches the current filters.</td></tr>';return;}body.innerHTML=rows.map(row=>{const rawUnit=row.inventory_unit_name||row.inventory_unit_symbol||'unit';const unit=unitLabel(rawUnit,Number(row.shelf_quantity));const priceUnit=unitLabel(rawUnit);const inactive=row.product_status!=='Active';const price=row.selling_price===null||row.selling_price===undefined?'—':`₱${Number(row.selling_price).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})}`;return `<tr data-product-id="${esc(row.product_id)}"><td><strong>${esc(row.brand_name||'N/A')}</strong></td><td>${productCell(row)}</td><td>${esc(specification(row))}</td><td>${esc(row.type_name||'N/A')}</td><td>${batchBadges(row)}</td><td><span class="qty-number">${esc(row.shelf_quantity)}</span><small class="d-block text-muted">${esc(unit)}</small></td><td><span class="selling-price">${esc(price)}</span><small class="d-block text-muted">per ${esc(priceUnit)}</small></td><td>${expiryBadge(row)}</td><td><span class="status-pill ${row.pos_status==='Available'?'is-available':'is-unavailable'}">${esc(row.pos_status)}</span></td><td><div class="table-actions"><button class="btn btn-outline-secondary shelf-details-btn" title="View Details" data-product-id="${esc(row.product_id)}"><i class="fa-solid fa-eye"></i></button><button class="btn btn-outline-primary selling-setup-btn" title="Selling Setup" data-product-id="${esc(row.product_id)}"><i class="fa-solid fa-tags"></i></button><button class="btn btn-outline-secondary return-storage-btn" title="Return to Storage" data-product-id="${esc(row.product_id)}" ${inactive?'disabled':''}><i class="fa-solid fa-arrow-rotate-left"></i></button></div></td></tr>`;}).join('');}

async function loadShelf(){try{const data=await PharmaUtils.safeFetch(`${API_BASE_URL}/inventory/get_shelf_inventory.php?t=${Date.now()}`,{credentials:'include'});const nextRows=data.data||[];if(shelfLoaded&&JSON.stringify(nextRows)===JSON.stringify(shelfRows))return;shelfRows=nextRows;shelfLoaded=true;const types=[...new Set(shelfRows.map(row=>text(row.type_name)).filter(Boolean))].sort();const select=document.getElementById('shelfTypeFilter');const current=select.value;select.innerHTML='<option value="">All Product Types</option>'+types.map(type=>`<option value="${esc(type)}">${esc(type)}</option>`).join('');select.value=current;render();}catch(error){PharmaUtils.toast.error(error.message);document.querySelector('#shelfInventoryTable tbody').innerHTML='<tr><td colspan="10" class="empty-row">Unable to load Shelf Inventory.</td></tr>';}}

function optionMarkup(option={}){const base=Number(option.base_quantity||1);return `<div class="selling-option-row" data-option-id="${esc(option.selling_option_id||'')}"><div><label class="form-label small fw-bold">Selling Unit</label><input class="form-control selling-option-unit" maxlength="50" required readonly value="${esc(option.unit||'')}"><small class="text-muted">Deducts ${esc(base)} ${esc(unitLabel(option.base_unit||'unit',base))}</small></div><div><label class="form-label small fw-bold">Inventory Deduction</label><input class="form-control selling-option-base" type="number" required readonly value="${esc(base)}"></div><div><label class="form-label small fw-bold">Selling Price per Unit</label><div class="input-group"><span class="input-group-text">₱</span><input class="form-control selling-option-price" type="number" min="0" step=".01" required value="${esc(Number(option.selling_price||0).toFixed(2))}"></div></div></div>`;}
function addOption(option={}){document.getElementById('sellingOptionsRows').insertAdjacentHTML('beforeend',optionMarkup(option));}
async function openSelling(productId){const row=shelfRows.find(item=>String(item.product_id)===String(productId));const data=await PharmaUtils.safeFetch(`${API_BASE_URL}/inventory/get_selling_options.php?product_id=${encodeURIComponent(productId)}&t=${Date.now()}`,{credentials:'include'});const unit=(data.base_unit&&data.base_unit.unit_name)||(data.base_unit&&data.base_unit.unit_symbol)||'Unit';const optionsByUnit=new Map((data.options||[]).map(option=>[text(option.unit).toLowerCase(),option]));const shelfQty=Number(row&&row.shelf_quantity!=null?row.shelf_quantity:(data.shelf_base_quantity||0));const usableShelf=Number(row&&row.usable_shelf_quantity!=null?row.usable_shelf_quantity:(data.shelf_usable_base_quantity!=null?data.shelf_usable_base_quantity:(data.shelf_base_quantity||0)));document.getElementById('sellingSetupProductId').value=productId;document.getElementById('sellingSetupProductName').textContent=productIdentity(row)||'Product';document.getElementById('sellingSetupBrand').textContent=(row&&row.brand_name)||'—';document.getElementById('sellingSetupGeneric').textContent=productGeneric(row)||'—';document.getElementById('sellingSetupSpecification').textContent=specification(row);document.getElementById('sellingSetupType').textContent=(row&&row.type_name)||'—';document.getElementById('sellingSetupBaseUnit').textContent=unitLabel(unit);document.getElementById('sellingSetupShelfQuantity').textContent=`${shelfQty} ${unitLabel(unit,shelfQty)}`;document.getElementById('sellingSetupUsableExpiry').textContent=row&&row.nearest_usable_expiry_date?`${row.nearest_usable_expiry_status}: ${formatDate(row.nearest_usable_expiry_date)}`:'No usable shelf stock';const container=document.getElementById('sellingOptionsRows');container.innerHTML='';const candidates=data.candidate_units&&data.candidate_units.length?data.candidate_units:[{unit:unitLabel(unit),base_quantity:1}];candidates.forEach((candidate,index)=>{const saved=optionsByUnit.get(text(candidate.unit).toLowerCase())||{};const base=Number(saved.base_quantity||candidate.base_quantity||1);const sellingPrice=saved.selling_price!=null?saved.selling_price:(data.base_unit&&data.base_unit.price!=null?data.base_unit.price:0);addOption({...candidate,...saved,unit:saved.unit||candidate.unit,base_quantity:base,base_unit:unit,selling_price:sellingPrice,available_quantity:Math.floor(usableShelf/Math.max(1,base)),pos_enabled:1,is_active:1,is_default:index===0?1:0});});bootstrap.Modal.getOrCreateInstance(document.getElementById('sellingSetupModal')).show();}
async function saveSelling(event){event.preventDefault();const options=[...document.querySelectorAll('.selling-option-row')].map((row,index)=>({selling_option_id:row.dataset.optionId||'',unit:row.querySelector('.selling-option-unit').value.trim(),base_quantity:Number(row.querySelector('.selling-option-base').value),selling_price:Number(row.querySelector('.selling-option-price').value),pos_enabled:1,is_active:1,is_default:index===0?1:0}));const button=document.getElementById('saveSellingSetupButton');button.disabled=true;try{const productId=document.getElementById('sellingSetupProductId').value;const data=await PharmaUtils.safeFetch(`${API_BASE_URL}/inventory/save_selling_options.php`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:productId,options})});bootstrap.Modal.getInstance(document.getElementById('sellingSetupModal'))?.hide();PharmaUtils.toast.success(data.message);shelfLoaded=false;await loadShelf();publishDataUpdate('product-updated',{productId});}catch(error){PharmaUtils.toast.error(error.message);}finally{button.disabled=false;}}
async function returnToStorage(productId){const row=shelfRows.find(item=>String(item.product_id)===String(productId));if(!row)return;const displayUnit=row.inventory_unit_symbol||row.inventory_unit_name||'unit';const transferUnit=row.inventory_unit_name||displayUnit;const result=await Swal.fire({title:'Return stock to Storage',html:`<p class="mb-2">${esc(productIdentity(row)||'Product')}</p><small>Available: ${Number(row.shelf_quantity)} ${esc(displayUnit)}</small>`,input:'number',inputLabel:`Quantity (${displayUnit})`,inputAttributes:{min:'1',max:String(row.shelf_quantity),step:'1'},showCancelButton:true,confirmButtonText:'Return to Storage',confirmButtonColor:'#4f46e5',preConfirm:value=>{const quantity=Number(value);if(!Number.isInteger(quantity)||quantity<1||quantity>Number(row.shelf_quantity)){Swal.showValidationMessage('Enter a valid whole quantity within Shelf availability.');return false;}return quantity;}});if(!result.isConfirmed)return;try{const data=await PharmaUtils.safeFetch(`${API_BASE_URL}/inventory/transfer_stock.php`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:productId,movement_type:'SHELF_TO_STORAGE',quantity:result.value,unit:transferUnit,request_id:globalThis.crypto?.randomUUID?.()||''})});PharmaUtils.toast.success(data.message);shelfLoaded=false;await loadShelf();publishDataUpdate('storage-updated',{productId});publishDataUpdate('shelf-updated',{productId});}catch(error){PharmaUtils.toast.error(error.message);}}

['shelfSearch','shelfTypeFilter','shelfStatusFilter'].forEach(id=>document.getElementById(id)?.addEventListener(id==='shelfSearch'?'input':'change',render));document.getElementById('shelfInventoryTable')?.addEventListener('click',event=>{const details=event.target.closest('.shelf-details-btn');const selling=event.target.closest('.selling-setup-btn');const returning=event.target.closest('.return-storage-btn');if(details)openShelfDetails(details.dataset.productId);if(selling)openSelling(selling.dataset.productId).catch(error=>PharmaUtils.toast.error(error.message));if(returning)returnToStorage(returning.dataset.productId);});document.getElementById('sellingSetupForm')?.addEventListener('submit',saveSelling);if(localStorage.getItem('theme')==='dark')document.body.classList.add('dark-mode');window.addEventListener('pharma:session-ready',loadShelf);setTimeout(()=>{if(!shelfLoaded)loadShelf();},500);createLiveSync({interval:2000,events:['shelf-updated','storage-updated','payment-completed','product-updated','po-received'],sync:loadShelf});
