import PharmaUtils from '../utils.js';
import { createLiveSync, publishDataUpdate } from './live_data.js?v=1';

const API_BASE_URL = window.location.port ? 'http://127.0.0.1/PharmacySystem_for_DocR/pharma-api/v1' : '../pharma-api/v1';
const SEP = PharmaUtils.productIdentitySeparator || ' • ';
let shelfRows = [];
let shelfLoaded = false;

const esc = value => String(value ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const text = value => String(value ?? '').trim();
const cleanNumber = value => text(value) && Number.isFinite(Number(value)) ? String(Number(value)) : text(value);
const measurement = (value,unit) => cleanNumber(value) ? `${cleanNumber(value)}${text(unit) ? ` ${text(unit)}` : ''}` : '';
const pretty = value => text(value) && !/\d/.test(text(value)) && text(value) === text(value).toLowerCase() ? text(value)[0].toUpperCase()+text(value).slice(1) : text(value);
function unique(parts){const seen=new Set();return parts.map(pretty).filter(part=>{const key=part.toLowerCase();if(!part||seen.has(key))return false;seen.add(key);return true;});}
function unitLabel(value,quantity=1){const raw=text(value)||'Unit';const normalized=raw.toLowerCase().replaceAll('.','');const singular=['pc','pcs','piece','pieces','each'].includes(normalized)?'Piece':raw.split(/\s+/).map(word=>word?word[0].toUpperCase()+word.slice(1).toLowerCase():'').join(' ');if(Number(quantity)===1||/s$/i.test(singular))return singular;if(/(?:x|z|ch|sh)$/i.test(singular))return `${singular}es`;return `${singular}s`;}
function specification(product){
    if(text(product.normalized_specification)){const inventoryUnit=unitLabel(product.inventory_unit_name||product.inventory_unit_symbol);return unique(text(product.normalized_specification).split(/\s*•\s*/).map(part=>{const content=part.match(/^(\d+(?:\.\d+)?)\s*(?:pc|pcs|piece|pieces)$/i);return content&&!/^pieces?$/i.test(inventoryUnit)?`${content[1]} Pieces per ${inventoryUnit}`:part;})).join(SEP);}
    const category=text(product.category_name).toLowerCase(); let parts=[];
    if(category==='medicine') parts=[product.generic_name,measurement(product.strength_value,product.strength_unit)||product.strength,measurement(product.net_content_value,product.net_content_unit),product.dosage_form];
    else if(category==='medical supply'||category==='medical supplies') parts=[product.medical_variant,product.medical_size,product.material,product.sterile_status];
    else { const weight=measurement(product.net_weight,product.unit); parts=[product.variant,weight?'':product.size,weight]; }
    return unique(parts.filter(text)).join(SEP)||'No specification available';
}
function formatDate(value){if(!value)return '-';const date=new Date(`${value}T00:00:00`);return Number.isNaN(date.getTime())?'-':date.toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});}
function expiryBadge(row){const status=text(row.expiry_status)||'N/A';const cls=status==='Safe'?'status-safe':status==='Expiring Soon'?'status-soon':status==='Expired'?'status-expired':'status-na';return `<span class="status-pill ${cls}">${esc(status)}</span><small class="d-block mt-1 text-muted">${esc(formatDate(row.nearest_expiry_date))}</small>`;}

function filteredRows(){const query=text(document.getElementById('shelfSearch')?.value).toLowerCase();const type=text(document.getElementById('shelfTypeFilter')?.value);const status=text(document.getElementById('shelfStatusFilter')?.value);return shelfRows.filter(row=>(!query||[row.brand_name,row.product_name,row.barcode,row.type_name,specification(row)].join(' ').toLowerCase().includes(query))&&(!type||row.type_name===type)&&(!status||row.pos_status===status));}
function render(){const body=document.querySelector('#shelfInventoryTable tbody');const rows=filteredRows();if(!rows.length){body.innerHTML='<tr><td colspan="9" class="empty-row">No transferred Shelf stock matches the current filters.</td></tr>';return;}body.innerHTML=rows.map(row=>{const rawUnit=row.inventory_unit_name||row.inventory_unit_symbol||'unit';const unit=unitLabel(rawUnit,Number(row.shelf_quantity));const priceUnit=unitLabel(rawUnit);const inactive=row.product_status!=='Active';const price=row.selling_price===null||row.selling_price===undefined?'—':`₱${Number(row.selling_price).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})}`;return `<tr data-product-id="${esc(row.product_id)}"><td><strong>${esc(row.brand_name||'N/A')}</strong></td><td><strong>${esc(row.product_name)}</strong></td><td>${esc(specification(row))}</td><td>${esc(row.type_name||'N/A')}</td><td><span class="qty-number">${esc(row.shelf_quantity)}</span><small class="d-block text-muted">${esc(unit)}</small></td><td><span class="selling-price">${esc(price)}</span><small class="d-block text-muted">per ${esc(priceUnit)}</small></td><td>${expiryBadge(row)}</td><td><span class="status-pill ${row.pos_status==='Available'?'is-available':'is-unavailable'}">${esc(row.pos_status)}</span></td><td><div class="table-actions"><button class="btn btn-outline-primary selling-setup-btn" title="Selling Setup" data-product-id="${esc(row.product_id)}"><i class="fa-solid fa-tags"></i></button><button class="btn btn-outline-secondary return-storage-btn" title="Return to Storage" data-product-id="${esc(row.product_id)}" ${inactive?'disabled':''}><i class="fa-solid fa-arrow-rotate-left"></i></button></div></td></tr>`;}).join('');}

async function loadShelf(){try{const data=await PharmaUtils.safeFetch(`${API_BASE_URL}/inventory/get_shelf_inventory.php?t=${Date.now()}`,{credentials:'include'});const nextRows=data.data||[];if(shelfLoaded&&JSON.stringify(nextRows)===JSON.stringify(shelfRows))return;shelfRows=nextRows;shelfLoaded=true;const types=[...new Set(shelfRows.map(row=>text(row.type_name)).filter(Boolean))].sort();const select=document.getElementById('shelfTypeFilter');const current=select.value;select.innerHTML='<option value="">All Product Types</option>'+types.map(type=>`<option value="${esc(type)}">${esc(type)}</option>`).join('');select.value=current;render();}catch(error){PharmaUtils.toast.error(error.message);document.querySelector('#shelfInventoryTable tbody').innerHTML='<tr><td colspan="9" class="empty-row">Unable to load Shelf Inventory.</td></tr>';}}

function optionMarkup(option={}){return `<div class="selling-option-row" data-option-id="${esc(option.selling_option_id||'')}"><div><label class="form-label small fw-bold">Selling / Inventory Unit</label><input class="form-control selling-option-unit" maxlength="50" required readonly value="${esc(option.unit||'')}"></div><div><label class="form-label small fw-bold">Inventory Deduction</label><input class="form-control selling-option-base" type="number" required readonly value="1"></div><div><label class="form-label small fw-bold">Selling Price per Unit</label><div class="input-group"><span class="input-group-text">₱</span><input class="form-control selling-option-price" type="number" min="0" step=".01" required value="${esc(Number(option.selling_price||0).toFixed(2))}"></div></div><input class="selling-option-pos" type="checkbox" checked hidden><input class="selling-option-active" type="checkbox" checked hidden><input class="selling-option-default" name="sellingOptionDefault" type="radio" checked hidden></div>`;}
function addOption(option={}){const container=document.getElementById('sellingOptionsRows');container.insertAdjacentHTML('beforeend',optionMarkup(option));if(!container.querySelector('.selling-option-default:checked'))container.querySelector('.selling-option-default')?.click();}
async function openSelling(productId){const row=shelfRows.find(item=>String(item.product_id)===String(productId));const data=await PharmaUtils.safeFetch(`${API_BASE_URL}/inventory/get_selling_options.php?product_id=${encodeURIComponent(productId)}&t=${Date.now()}`,{credentials:'include'});const unit=data.base_unit?.unit_name||data.base_unit?.unit_symbol||'Unit';const canonical=(data.options||[]).find(option=>Number(option.base_quantity)===1)||{};document.getElementById('sellingSetupProductId').value=productId;document.getElementById('sellingSetupProductName').textContent=row?.product_name||'Product';document.getElementById('sellingSetupBaseUnit').textContent=unitLabel(unit);document.getElementById('sellingSetupShelfQuantity').textContent=`${Number(data.shelf_base_quantity||0)} ${unitLabel(unit,Number(data.shelf_base_quantity||0))}`;const container=document.getElementById('sellingOptionsRows');container.innerHTML='';addOption({...canonical,unit:unitLabel(unit),base_quantity:1,selling_price:canonical.selling_price??data.base_unit?.price??0,pos_enabled:1,is_active:1,is_default:1});bootstrap.Modal.getOrCreateInstance(document.getElementById('sellingSetupModal')).show();}
async function saveSelling(event){event.preventDefault();const options=[...document.querySelectorAll('.selling-option-row')].map(row=>({selling_option_id:row.dataset.optionId||'',unit:row.querySelector('.selling-option-unit').value.trim(),base_quantity:Number(row.querySelector('.selling-option-base').value),selling_price:Number(row.querySelector('.selling-option-price').value),pos_enabled:+row.querySelector('.selling-option-pos').checked,is_active:+row.querySelector('.selling-option-active').checked,is_default:+row.querySelector('.selling-option-default').checked}));const button=document.getElementById('saveSellingSetupButton');button.disabled=true;try{const productId=document.getElementById('sellingSetupProductId').value;const data=await PharmaUtils.safeFetch(`${API_BASE_URL}/inventory/save_selling_options.php`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:productId,options})});bootstrap.Modal.getInstance(document.getElementById('sellingSetupModal'))?.hide();PharmaUtils.toast.success(data.message);shelfLoaded=false;await loadShelf();publishDataUpdate('product-updated',{productId});}catch(error){PharmaUtils.toast.error(error.message);}finally{button.disabled=false;}}
async function returnToStorage(productId){const row=shelfRows.find(item=>String(item.product_id)===String(productId));if(!row)return;const displayUnit=row.inventory_unit_symbol||row.inventory_unit_name||'unit';const transferUnit=row.inventory_unit_name||displayUnit;const result=await Swal.fire({title:'Return stock to Storage',html:`<p class="mb-2">${esc(row.product_name)}</p><small>Available: ${Number(row.shelf_quantity)} ${esc(displayUnit)}</small>`,input:'number',inputLabel:`Quantity (${displayUnit})`,inputAttributes:{min:'1',max:String(row.shelf_quantity),step:'1'},showCancelButton:true,confirmButtonText:'Return to Storage',confirmButtonColor:'#4f46e5',preConfirm:value=>{const quantity=Number(value);if(!Number.isInteger(quantity)||quantity<1||quantity>Number(row.shelf_quantity)){Swal.showValidationMessage('Enter a valid whole quantity within Shelf availability.');return false;}return quantity;}});if(!result.isConfirmed)return;try{const data=await PharmaUtils.safeFetch(`${API_BASE_URL}/inventory/transfer_stock.php`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:productId,movement_type:'SHELF_TO_STORAGE',quantity:result.value,unit:transferUnit,request_id:globalThis.crypto?.randomUUID?.()||''})});PharmaUtils.toast.success(data.message);shelfLoaded=false;await loadShelf();publishDataUpdate('storage-updated',{productId});publishDataUpdate('shelf-updated',{productId});}catch(error){PharmaUtils.toast.error(error.message);}}

['shelfSearch','shelfTypeFilter','shelfStatusFilter'].forEach(id=>document.getElementById(id)?.addEventListener(id==='shelfSearch'?'input':'change',render));document.getElementById('shelfInventoryTable')?.addEventListener('click',event=>{const selling=event.target.closest('.selling-setup-btn');const returning=event.target.closest('.return-storage-btn');if(selling)openSelling(selling.dataset.productId).catch(error=>PharmaUtils.toast.error(error.message));if(returning)returnToStorage(returning.dataset.productId);});document.getElementById('sellingSetupForm')?.addEventListener('submit',saveSelling);document.getElementById('addSellingOptionButton')?.addEventListener('click',()=>addOption({pos_enabled:1,is_active:1}));document.getElementById('sellingOptionsRows')?.addEventListener('click',event=>{const remove=event.target.closest('.selling-option-remove');if(!remove)return;const container=document.getElementById('sellingOptionsRows');if(container.children.length<=1)return PharmaUtils.toast.warning('At least one Selling Option is required.');const wasDefault=remove.closest('.selling-option-row').querySelector('.selling-option-default').checked;remove.closest('.selling-option-row').remove();if(wasDefault)container.querySelector('.selling-option-default')?.click();});if(localStorage.getItem('theme')==='dark')document.body.classList.add('dark-mode');window.addEventListener('pharma:session-ready',loadShelf);setTimeout(()=>{if(!shelfLoaded)loadShelf();},500);createLiveSync({interval:2000,events:['shelf-updated','storage-updated','payment-completed','product-updated','po-received'],sync:loadShelf});
